name: Deploy to Ec2 With Docker Blue/Green
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set YML
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          find src
          echo "${{ secrets.JWT_YML }}" | base64 --decode > src/main/resources/jwt.yml
          find src
      
      - name: Build with Gradle  
        working-directory: ./  
        run: |  
          chmod +x ./gradlew  
          ./gradlew bootJar 

      - name: Build Docker image
        working-directory: ./
        run: |
          docker build -t ticketpaper2/logeat-backend:blue -f Dockerfile .
          docker build -t ticketpaper2/logeat-backend:green -f Dockerfile .
      
      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images to DockerHub
        run: |
          docker push ticketpaper2/logeat-backend:blue
          docker push ticketpaper2/logeat-backend:green
      - name: EC2 SSH Login and Docker run with Blue/Green Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            ./deploy.sh


            
            echo "Deployed $NEW_VERSION version"
            # 이전 버전의 이미지 삭제 또는 보관 로직 추가 (선택적)
